### ISSUE TITLE
Attempting conversion fails with a type error in 0xc-string-to-number

### ISSUE THREAD

**Issue by ylluminarious** [AdamNiederer/0xc#2]
Hi,

I tried using `0xc` after installing it from MELPA. I tried to do a simple conversion of the number 10 to hexadecimal, just to get a feel for how this works. However, everything I try seems to end up with this error:

```
0xc-string-to-number: Wrong type argument: stringp, nil
```

This error occurs when I try `0xc-convert-point` as well. I'm not sure whether I'm just using this package incorrectly or if this is a bug. In either case, there's not enough documentation here for me to tell. FYI, I'm using Emacs 25.1.1 on OS X 10.11.6.

**Comment by AdamNiederer** [comment]
Shoot, thanks for catching this. Forgot to use let\* in the interactive portion of `0xc-convert`. Should be fixed in the referenced commit.

**Comment by ylluminarious** [comment]
@AdamNiederer Ok, great. Thanks!
