### ISSUE TITLE
No description available.

### ISSUE THREAD

**Issue by ahungry** [AdamNiederer/0xc#4]
In the package listing (`M-x list-packages`) this package is missing it's description.

You should add something like this into the comments at top of the file:
```lisp
;;; 0xc.el --- Base 10 number conversion utility.
```

**Comment by ahungry** [comment]
Oh weird, it currently is present in your source, but not in what list-packages is displaying.  Was this recently fixed?  Or is list-packages failing to parse due to the package .el file starting with a digit or something?

**Comment by AdamNiederer** [comment]
I honestly don't know what's causing it. It worked for a few weeks and then disappeared. 4clojure has a correct description, so its probably not the number in the name.

**Comment by AdamNiederer** [comment]
Triggering a MELPA rebuild fixed the issue. I'll re-open if it reoccurs.
