### ISSUE TITLE
Convert all the numbers in the buffer

### ISSUE THREAD

**Issue by rhymer** [AdamNiederer/0xc#6]
Do you think if it's useful to provide a function that converts all the hex numbers in the buffer to decimal numbers? 
For example, something like `0xc-convert-buffer` that converts
```
<tag1>0x4</tag1>
<tag2>0x3</tag2>
<tag3>0x1 0x2 0x3<tag3>
```
to
```
<tag1>4</tag1>
<tag2>3</tag2>
<tag3>1 2 3<tag3>
```
I imagine this can be done by `re-search-forward` for `0x[0-9a-f]+` and call `0xc-convert-point`?

**Comment by exchg** [comment]
This will be definitely useful!
But even more useful will be to do conversion in the region and rectangle.

**Comment by AdamNiederer** [comment]
I have authored a more generic solution to this problem: https://github.com/AdamNiederer/metamorph, which should hopefully find its way into MELPA (ref https://github.com/melpa/melpa/pull/5735)

To use metamorph in your example:

```xml
<tag1>0x4</tag1>
<tag2>0x3</tag2>
<tag3>0x1 0x2 0x3<tag3>
```

Highlight the numbers, type `metamorph-map-region RET 0x[0-9]+ RET (0xc-convert 10 %) RET`, and it will transform your buffer as such:

```xml
<tag1>4</tag1>
<tag2>3</tag2>
<tag3>1 2 3<tag3>
```

I'm going to close this, as I think this is a reasonably elegant solution and I'm not sure I could do much better by tightly integrating it into `0xc`.
